function [m, I, d] = Mcalculator(X)
M_WHEEL = 6; RADIUS_WHEEL = 0.0825; DIST_WHEELS = 0.342; I_WHEEL = 0.03; 
m = (X(1)+X(2)-I_WHEEL)/(1/2*RADIUS_WHEEL*RADIUS_WHEEL);
I = (X(1)-X(2)-I_WHEEL)/(1/2*RADIUS_WHEEL*RADIUS_WHEEL/(DIST_WHEELS*DIST_WHEELS));
d = 2*DIST_WHEELS*X(3)/(m-2*M_WHEEL)/(RADIUS_WHEEL*RADIUS_WHEEL);
end